# Generated by Django 3.2.9 on 2021-11-17 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', height_field='200', null=True, upload_to='', width_field='200'),
        ),
    ]
